src/Entity/Application.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ApplicationRepository")
 */
class Application
{
    const STATUS = [
        0 => 'Pending',
        1 => 'Accepted',
        2 => 'Rejected'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="applications")
     */
    private $staffuser;

    /**
     * @ORM\Column(type="integer", options={"default":"0"})
     */
    private $status;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Student", mappedBy="application", cascade={"persist", "remove"})
     */
    private $student;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStaffuser(): ?User
    {
        return $this->staffuser;
    }

    public function setStaffuser(?User $staffuser): self
    {
        $this->staffuser = $staffuser;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }
    public function getStatusType(): String
    {
        return self::STATUS[$this->status];
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(Student $student): self
    {
        $this->student = $student;

        // set the owning side of the relation if necessary
        if ($student->getApplication() !== $this) {
            $student->setApplication($this);
        }

        return $this;
    }
}

src/Entity/Student.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StudentRepository")
 */
class Student
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="date")
     */
    private $date_of_birth;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $home_address;

    /**
     * @ORM\Column(type="integer")
     */
    private $national_id_number;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="student", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Document", mappedBy="student", cascade={"persist", "remove"})
     */
    private $documents;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\AcademicData", inversedBy="student", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     * @Assert\Valid()
     */
    private $academicdata;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Application", inversedBy="student", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $application;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Background", inversedBy="student", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $background;

    public function __construct()
    {
        $this->documents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(\DateTimeInterface $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getHomeAddress(): ?string
    {
        return $this->home_address;
    }

    public function setHomeAddress(string $home_address): self
    {
        $this->home_address = $home_address;

        return $this;
    }

    public function getNationalIdNumber(): ?int
    {
        return $this->national_id_number;
    }

    public function setNationalIdNumber(int $national_id_number): self
    {
        $this->national_id_number = $national_id_number;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Document[]
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(Document $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->setStudent($this);
        }

        return $this;
    }

    public function removeDocument(Document $document): self
    {
        if ($this->documents->contains($document)) {
            $this->documents->removeElement($document);
            // set the owning side to null (unless already changed)
            if ($document->getStudent() === $this) {
                $document->setStudent(null);
            }
        }

        return $this;
    }

    public function getAcademicdata(): ?AcademicData
    {
        return $this->academicdata;
    }

    public function setAcademicdata(AcademicData $academicdata): self
    {
        $this->academicdata = $academicdata;

        return $this;
    }

    public function getApplication(): ?Application
    {
        return $this->application;
    }

    public function setApplication(Application $application): self
    {
        $this->application = $application;

        return $this;
    }

    public function getBackground(): ?Background
    {
        return $this->background;
    }

    public function setBackground(Background $background): self
    {
        $this->background = $background;

        return $this;
    }
}

src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\Student;
use App\Entity\College;
use App\Entity\AcademicData;
use App\Entity\Application;
use App\Entity\Document;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'constraints' => [new NotBlank(['message' => 'Your name may not be blank'])
            ],
            'label' => 'Last Name',
            /*'help' => 'Write your name',*/
            /*'attr' => ['placeholder' => 'Pabich','class'=>''],*/
            ])
            ->add('firstname', TextType::class, [
                'constraints' => [new NotBlank(['message' => 'Your firstname may not be blank'])
            ],
            'label' => 'First Name',
            /*'help' => 'Write your Firstname',*/
            /*'attr' => ['placeholder' => 'Florian'],*/
            ])
            ->add('date_of_birth', DateType::class, [
                'placeholder' => [
                    'day' => 'Day', 'month' => 'Month', 'year' => 'Year', 
                ],
                'format' => 'ddMMMMyyyy',
                'years' => range(1900,2020)
            ])
            ->add('home_address', TextareaType::class, [
                'constraints' => [new NotBlank(['message' => 'Your home address may not be blank'])
            ],
                'label' => 'Home Address',
                /*'help' => 'Write your address',*/
                'attr' => ['placeholder' => 'الجادرية، Baghdad, Irak'],
            ])
            ->add('national_id_number', IntegerType::class, [
                'label' => 'National ID number',
                'help' => 'Enter your national ID number (which is given on your student card',
                'attr' => ['placeholder' => '0123456'],
            ])
            /*->add('college', EntityType::class, [
                'class' => College::class,
                'choice_label' => 'name',
                'multiple' => false,
                'required' => false
            ])*/

            ->add('background', BackgroundType::class)
            ->add('academicdata', AcademicDataType::class)
            ->add('application', ApplicationType::class)
            #->add('documents', DocumentType::class)
            /*->add('documents', DocumentType::class, [
                #'class' => Document::class,
                #'choice_label' => 'imageFile',
            ])*/

            /**->add('documents', CollectionType::class, [
                'class' => Document::class,
                'type' => new DocumentType(),
                'allow_add' => true,
                'allow_delete' => true,
                'label' => false,
                #'entry_type' => DocumentType::class,
            ])**/
            #->add('user')
            #->add('academicdata')
            #->add('application')
            #->add('background')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
        ]);
    }
}

src/Controller/Student/FormulaireController.php
<?php

namespace App\Controller\Student;

use App\Entity\Student;
use App\Form\StudentType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class FormulaireController extends AbstractController
{
    
    public function index()
    {
        return $this->render('formulaire/index.html.twig', [
            'controller_name' => 'FormulaireController',
        ]);
    }

    /**
     * @Route("/student/formulaire", name="formulaire")
     */
	public function fillform(Request $request)
	{
		$student = new Student();
		$form_student = $this->createForm(StudentType::class, $student);
		$form_student->handleRequest($request);

		if($form_student->isSubmitted() && $form_student->isValid())
		{
			
			$student->setUser($this->getUser());

			#$student->setAcademicData();
			#$student->setApplication(1);
			#$student->setBackground(1);
			$entityManager = $this->getDoctrine()->getManager();
			$entityManager->persist($student);
			$entityManager->flush();
			return $this->redirectToRoute('student_index');
			#return $this->redirectToRoute("app_question", ['id' => $question->getId()]);
		}

		return $this->render('student/formulaire/index.html.twig', [
			'studentForm' => $form_student->createView()
		]);
	}


}

src/Controller/Student/ResumePageController.php
<?php

namespace App\Controller\Student;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use App\Repository\ApplicationRepository;
use App\Repository\DocumentRepository;

/**
 * @Route("/student", methods={"GET"})
*/
class ResumePageController extends AbstractController
{
    /**
     * @Route("/", name="student_index")
     */
    public function index(ApplicationRepository $applicationRepository, DocumentRepository $documentRepository): Response
    {
    	$tempid = $this->getUser()->getStudent();
        if ($this->getUser()->getStudent()== null) {
            return $this->redirectToRoute("formulaire");
        };
        if ($tempid != null) {
           $tempid =  $this->getUser()->getStudent()->getApplication()->getId();
        }
        
    	$application = $applicationRepository->findBy([
    		'id' => $tempid
    	]);
        return $this->render('student/index.html.twig', [
            'application' => $application,
            'documents' => $documentRepository->findBy(
                ['student' => $this->getUser()->getStudent()->getId()])
        ]);
    }
}

src/Controller/Student/UniversityProposalController.php
<?php

namespace App\Controller\Student;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;




class UniversityProposalController extends AbstractController
{
    /**
     * @Route("/university/proposal", name="university_proposal")
     */
    public function index()
    {


        return $this->render('student/university_proposal.html.twig', [
            'controller_name' => 'UniversityProposalController',

        ]);
    }
}

templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Application index{% endblock %}

{% block body %}

    <div class="container">

        <br></br>

        <div class="row">

            <h1 class="col-lg-12 text-center">Status of your application</h1>

        </div>

        <br></br>


        <div class="row">

                {% if application %}
                    <table class="col-lg-12 table-center table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for application in application %}
                            <tr>
                                <td>{{ application.id }}</td>
                                <td>{{ application.statusType }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <tr>
                        <h5>You don't have any application</h5>
                    </tr>
                    <a href="{{ path('formulaire') }}">Create new</a>
                {% endif %}
        </div>

        <br></br>

        <div class="row">

            <p>Click on the "Universities proposal" button if your application is rejected. You will be redirected to other universities in Baghdad that might have available place for you.</p>
            <a href="{{ path('university_proposal') }}" class="btn-primary btn-block text-center text-dark btn-outline-default">Universities proposal</a>

        </div>

            {{ include('document/index.html.twig')}}
    </div>

{% endblock %}

templates/student/university_proposal.html.twig
{% extends 'base.html.twig' %}

{% block title %}University proposal{% endblock %}

{% block body %}

	<div class="container">

		<br></br>

		<div class="row">

			<h1 class="col-lg-12 text-center">Universities proposal</h1>

		</div>

		<br></br>

		<div class="row col-lg-12 text-center">

			<p>In case your application has been rejected by Baghdad University, here are other universities in Baghdad that may have some place for you.</p>
			<br></br>
			<p>We apologize and wish you the best for the future.</p>

		</div>

		<div class="row"></div>

			<table class="col-lg-12 table-center table-bordered table-striped">
	            
	                <thead class="thead-light">
	                    <tr class="text-center">
	                        
	                        <th>University Name</th>
	                        <th>Website</th>
	                        <th>Available capacity</th>
	                        
	                    </tr>

	                </thead>

	                <tbody>

	                    <tr>
	                       
	                        <td>University of Baghdad (1958)</td>
	                        <td><a href="http://www.en.uobaghdad.edu.iq">www.en.uobaghdad.edu.iq</a></td>
	                        <td>70615</td>
	                        
	                    </tr>
	                    <tr>
	                       
	                        <td>Mustansiriyah University (1963)</td>
	                        <td><a href="http://www.uomustansiriyah.edu.iq">www.uomustansiriyah.edu.iq</a></td>
	                        <td>37572</td>
	                        
	                    </tr>
	                    <tr>
	                       
	                        <td>University of Technology (1975)</td>
	                        <td><a href="http://www.uotechnology. edu.iq ">www.uotechnology. edu.iq </a></td>
	                        <td>7116</td>
	                        
	                    </tr>
	                    <tr>
	                       
	                        <td>Al-Nahrain University (1987)</td>
	                        <td><a href="http://www.nahrainuniv.edu.iq/ar ">www.nahrainuniv.edu.iq/ar </a></td>
	                        <td>3684</td>
	                        
	                    </tr>
	                    <tr>
	                       
	                        <td>AI-iraqia university (1989)</td>
	                        <td><a href="http://www.aliraqia.edu.iq">www.aliraqia.edu.iq</a></td>
	                        <td>23310</td>
	                        
	                    </tr>
	                    <tr>
	                       
	                        <td>Al-karkh University for Science (2014)</td>
	                        <td><a href="http://www.kus.edu.iq ">www.kus.edu.iq </a></td>
	                        <td>500</td>
	                        
	                    </tr>
	                    <tr>
	                       
	                        <td>University of information Technology & Communications (2014)</td>
	                        <td><a href="http://www.uoitc.edu.iq">www.uoitc.edu.iq</a></td>
	                        <td>500</td>
	                        
	                    </tr>
	                    <tr>
	                       
	                        <td>Middle Technical University (2014)</td>
	                        <td><a href="http://www.mtu.edu.iq">www.mtu.edu.iq</a></td>
	                        <td>40758</td>
	                        
	                    </tr>
	                    <tr>
	                       
	                        <td>IbnSina University of Medical and Pharmaceutical Sciences (2014)</td>
	                        <td><a href="http://www.Ibnsina.edu.iq">www.Ibnsina.edu.iq</a></td>
	                        <td>732</td>
	                        
	                    </tr>
	                
	                </tbody>
	            </table>
		</div>
	</div>

{% endblock %}