src/Entity/Document.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DocumentRepository")
 * @Vich\Uploadable()
 */
class Document
{
    const TYPE = [
        0 => 'Home Address Evidence',
        1 => 'National Identification Evidence',
        2 => 'Student Card Evidence',
        3 => 'Security Reason Evidence',
        4 => 'Previous University Evidence',
        5 => 'Previous Semester Evidence',
    ];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $filename;


    /**
     * @Vich\UploadableField(mapping="document_images", fileNameProperty="filename")
     * @var File|null
     **/
    private $imageFile;

    /**
     * @ORM\Column(type="integer", options={"default":"0"})
     */
    private $type;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface|null
     */
    private $updatedAt;



    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Student", inversedBy="documents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $student;


    public function __construct()
    {
        $this->documents = new ArrayCollection();
        $this->updatedAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(?string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(File $imageFile)
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updatedAt = new \DateTime('now');
        }
        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }
    public function getTypeType(): String
    {
        return self::TYPE[$this->type];
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(?Student $student): self
    {
        $this->student = $student;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

src/Form/DocumentType.php
<?php

namespace App\Form;

use App\Entity\Document;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Vich\UploaderBundle\Form\Type\VichImageType;


class DocumentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            /*->add('imageFile', VichImageType::class, [
                'label' => 'update',
                'asset_helper' => true,
            ])*/
            ->add('imageFile', FileType::class)
            ->add('type', ChoiceType::class, [
                #'choices' => Property::HEAT
                'choices' => $this->getChoices()
            ])
            #->add('student')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Document::class,
        ]);
    }
    private function getChoices()
    {
        $choices = Document::TYPE;
        $output = [];
        foreach($choices as $k => $v)
        {
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/DocumentController.php
<?php

namespace App\Controller;

use App\Entity\Document;
use App\Form\DocumentType;
use App\Repository\DocumentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/document")
 */
class DocumentController extends AbstractController
{
    /**
     * @Route("/", name="document_index", methods={"GET"})
     */
    public function index(DocumentRepository $documentRepository): Response
    {
        return $this->render('document/index.html.twig', [
            'documents' => $documentRepository->findBy(
                ['student' => $this->getUser()->getStudent()->getId()
            ]),
        ]);
    }

    /**
     * @Route("/new", name="document_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $document = new Document();
        $form = $this->createForm(DocumentType::class, $document);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $document->setStudent($this->getUser()->getStudent());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($document);
            $entityManager->flush();

            return $this->redirectToRoute('student_index');
        }

        return $this->render('document/new.html.twig', [
            'document' => $document,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="document_show", methods={"GET"})
     */
    public function show(Document $document): Response
    {
        return $this->render('document/show.html.twig', [
            'document' => $document,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="document_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Document $document): Response
    {
        $form = $this->createForm(DocumentType::class, $document);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('student_index');
        }

        return $this->render('document/edit.html.twig', [
            'document' => $document,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="document_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Document $document): Response
    {
        if ($this->isCsrfTokenValid('delete'.$document->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($document);
            $entityManager->flush();
        }

        return $this->redirectToRoute('student_index');
    }
}

templates/document/_delete_form.html.twig
<form method="post" action="{{ path('document_delete', {'id': document.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ document.id) }}">
    <button class="btn btn-danger btn-sm btn-block">Delete</button>
</form>

templates/document/_form.html.twig
<div class="row col-lg-12 center-block">

		{{ form_start(form) }}
		    {{ form_widget(form) }}
		    <button class="btn btn-block text-center text-dark btn-outline-secondary">{{ button_label|default('Save') }}</button>
		{{ form_end(form) }}

</div>

templates/document/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Document{% endblock %}

{% block body %}

	<div class="container">

		<br></br>

		<div class="row">

    		<h1 class="col-lg-12 text-center">Edit Document</h1>

    	</div>

    	<div class="row col-lg-12">

    		{{ include('document/_form.html.twig', {'button_label': 'Update'}) }}

    	</div>

    	<br></br>

    	<div class="row">

    		<a href="{{ path('document_index') }}" class="btn btn-primary btn-sm" role="button" style="width:100%;">Back to list</a>

    	</div>

    	<div class="row col-lg-12 btn-group-justified btn-center btn-block" style="width:100%;">

    		{{ include('document/_delete_form.html.twig') }}

    	</div>

    </div>

{% endblock %}

templates/document/index.html.twig
{% block body %}

    <div class="container">

        <br></br>

        <div class="row">

            <h1 class="col-lg-12 text-center">Documents Uploaded</h1>

        </div>

        <br></br>

        <div class="row">
    
            {% if not is_granted('ROLE_ADMIN') %}

                <p>Please, upload your evidences here.</p>

            {% endif %}

        </div>

        <div class="row">

            <table class="col-lg-12 table-center table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Filename</th>
                        <th>Type</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>

                    {% for document in documents %}

                        <tr>
                            <td>{{ document.filename }}</td>
                            <td>{{ document.typeType }}</td>
                            <td>
                                <a href="{{ path('document_show', {'id': document.id}) }}" class="btn btn-default btn-outline-secondary btn-sm" role="button" style="width:50%;">show</a>
                                {% if not is_granted('ROLE_ADMIN') %}
                                <a href="{{ path('document_edit', {'id': document.id}) }}" class="btn btn-default btn-outline-secondary btn-sm" role="button" style="width:50%;">edit</a>

            {% endif %}
                            </td>
                        </tr>

                    {% else %}

                        <tr>
                            <td colspan="6">no records found</td>
                        </tr>

                    {% endfor %}

                </tbody>

            </table>

        </div>

        <br></br>

        <div class="row">

            {% if not is_granted('ROLE_ADMIN') %}

                <a href="{{ path('document_new') }}" class="btn-primary btn-block text-center text-dark btn-outline-default">Upload new evidence</a>

            {% endif %}

        </div>

    
{% endblock %}

templates/document/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Document{% endblock %}

{% block body %}

	<div class="container">

		<br></br>

		<div class="row">

    		<h1 class="col-lg-12 text-center">Add new Document</h1>

    	</div>

    	<br></br>

    	<div class="row">

    		<div class="col-lg-12">

    			{{ include('document/_form.html.twig') }}

    		</div>

    	</div>

    	<br></br>
    

    	<a href="{{ path('document_index') }}" class="btn-primary btn-block text-center text-dark btn-outline-default">Back to list</a>

    </div>
{% endblock %}

templates/document/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Document{% endblock %}

{% block body %}

    <div class="container">

        <br></br>

        <div class="row">
        
            <h1 class="col-lg-12 text-center">Document</h1>

        </div>

        <br></br>

        <div class="row">

            <table class="col-lg-12 table-center table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>Filename</th>
                        <td>{{ document.filename }}</td>
                    </tr>
                    <tr>
                        <th>Type</th>
                        <td>{{ document.typeType }}</td>
                    </tr>
                    <tr>
                        <th>UpdatedAt</th>
                        <td>{{ document.updatedAt ? document.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                    </tr>
                    <tr>
                        <th>Image</th>
                        <img src="{{ vich_uploader_asset(document, 'imageFile')  }}" class="" style="width: 100%; height:auto;">
                        <td><a href="{{ vich_uploader_asset(document, 'imageFile') }}" />Display</a></td>
                    </tr>
                </tbody>
            </table>

        </div>

        <br></br>

        <div class="row">
    
            {% if not is_granted('ROLE_ADMIN') %}

                <a href="{{ path('student_index') }}" class="btn btn-primary btn-sm" role="button" style="width:50%;">Back to list</a>

                <a href="{{ path('document_edit', {'id': document.id}) }}" class="btn btn-primary btn-sm" role="button" style="width:50%;">Edit</a>

        </div>

        <div class="row col-lg-12 btn-group-justified btn-center btn-block" style="width:100%;">

                {{ include('document/_delete_form.html.twig') }}

            {% endif %}

        </div>
    </div>
{% endblock %}